### ISSUE TITLE
Different config variables and support for path rewriting

### ISSUE THREAD

**Issue by phbaudin** [multidimension-al/phpbbauth#4]
Great tool! It does however use two different config variables, $wgPhpbbAuthForumDirectory and $wgPhpBBAuthForumDirectory, where only the case differs.

While merging them would solve that, wikis making use of path rewriting could use two path variables, one to the forum where it appears to be to URL-rewritten links (for hyperlinks), and one to the internal files of the forums (for file inclusion).

**Comment by phbaudin** [comment]
The temporary fix I'm using is simply to replace:
`'logout' => $wgPhpbbAuthForumDirectory . 'ucp.php?mode=logout&sid=' . $user->session_id`
with
`'logout' => $wgPhpBBAuthForumDirectory . 'ucp.php?mode=logout&sid=' . $user->session_id`
on line 54 in Phpbbauth/PhpbbAuth.php

Because of a bug in the current code, both `$wgPhpbbAuthForumDirectory` and `$wgPhpBBAuthForumDirectory` (note the caps) need to be set for everything to work properly, so this quick fix allows me to use one variable for the location in the file system and the other for the URL.

I guess it's just a matter of giving those two variables clear, distinct names and we should be good.

**Comment by ajquick** [comment]
I took two approaches for this. First I introduced a seperate variable named: 

_$wgPhpbbAuthAbsolutePath_ 

This would be defined like:

`$wgPhpbbAuthAbsolutePath = '//www.domain.com/forum/';`

You can also change the setting in your phpBB installation iteself, to specify the domain and settings in "Server Settings". If **Force server URL settings** is turned on, it will take those variables specified there for the direct url to the variable.

**Comment by ajquick** [comment]
Fixed in version v0.0.6: https://github.com/multidimension-al/phpbbauth/releases/tag/0.0.6
